# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_progressitem_staffitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='caption',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bug',
            name='comment',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='comment',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='progressitem',
            name='caption',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='progressitem',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='staffitem',
            name='caption',
            field=models.CharField(max_length=255),
        ),
    ]
