# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20160301_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
    ]
